version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped