export const HTTP_EXCEPTIONS = [
    { exception: 'BadRequestException', code: 400, message: 'Dữ liệu đầu vào không hợp lệ' },
    { exception: 'UnauthorizedException', code: 401, message: 'Chưa đăng nhập / Token sai' },
    { exception: 'PaymentRequiredException', code: 402, message: 'Tài nguyên yêu cầu thanh toán (hiếm dùng)' },
    { exception: 'ForbiddenException', code: 403, message: 'Đã đăng nhập nhưng không đủ quyền' },
    { exception: 'NotFoundException', code: 404, message: 'Không tìm thấy tài nguyên' },
    { exception: 'MethodNotAllowedException', code: 405, message: 'Gọi sai HTTP method (VD: dùng POST cho route chỉ chấp nhận GET)' },
    { exception: 'NotAcceptableException', code: 406, message: 'Client không chấp nhận định dạng trả về' },
    { exception: 'RequestTimeoutException', code: 408, message: 'Server mất quá nhiều thời gian để xử lý request' },
    { exception: 'ConflictException', code: 409, message: 'Trùng dữ liệu (VD: email đã tồn tại)' },
    { exception: 'GoneException', code: 410, message: 'Tài nguyên từng tồn tại nhưng giờ không còn' },
    { exception: 'PayloadTooLargeException', code: 413, message: 'Dữ liệu gửi lên quá lớn' },
    { exception: 'UnsupportedMediaTypeException', code: 415, message: 'Định dạng media không được hỗ trợ' },
    { exception: 'UnprocessableEntityException', code: 422, message: 'Dữ liệu hợp lệ về cấu trúc nhưng sai về logic (VD: sai định dạng email)' },
    { exception: 'InternalServerErrorException', code: 500, message: 'Lỗi không xác định ở phía server' },
    { exception: 'NotImplementedException', code: 501, message: 'Chức năng chưa được hiện thực' },
    { exception: 'BadGatewayException', code: 502, message: 'Gateway nhận phản hồi không hợp lệ từ server khác' },
    { exception: 'ServiceUnavailableException', code: 503, message: 'Server tạm thời quá tải hoặc bảo trì' },
    { exception: 'GatewayTimeoutException', code: 504, message: 'Server làm trung gian mất quá nhiều thời gian chờ phản hồi' },
];
