version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-nest
    ports:
      - "5672:5672"     # Cổng AMQP để service kết nối
      - "15672:15672"   # Giao diện quản lý RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq
      - user-service
      - shipment-service
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: unless-stopped

  shipment-service:
    build:
      context: ./shipment-service
      dockerfile: Dockerfile
    container_name: shipment-service
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://user:password@localhost:5672
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
