version: '3.8'
services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on:
      - user-service
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2001:db8:2::/64"
